[www]
clear_env = no
env[DB_HOST] = diklat_db
env[DB_PORT] = 3306
env[DB_DATABASE] = sistem_diklat
env[DB_USERNAME] = diklat_user
env[DB_PASSWORD] = "Password123!"
env[CACHE_STORE] = file
env[SESSION_DRIVER] = file
env[QUEUE_CONNECTION] = sync
env[APP_KEY] = "base64:UiGcc6G3JUG0sMx176lHU2u5c3vbXWcOAaB9yFVQs5s="
env[APP_ENV] = production
env[APP_URL] = http://localhost:8090
